---
- name: Deploy engaging website
  hosts: myvms
  become: yes
  
  vars:
    html_file_path: /home/shira/Desktop/index.html

  tasks:
    - name: Update the package cache
      apt:
        update_cache: yes

    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Copy index.html to the web server's root
      copy:
        src: "{{ html_file_path }}"  # Use the variable here
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Ensure Apache2 is running
      service:
        name: apache2
        state: started
        enabled: yes

